version: '3.1'

services:
    mixpost:
        image: inovector/mixpost:latest
        environment:
            APP_NAME: 'Mixpost'
            APP_KEY: example_secret_key # Generate a base64 secret with this tool: https://mixpost.app/encryption-key-generator
            APP_URL: https://example.com
            DB_DATABASE: '${DB_NAME}'
            DB_USERNAME: '${DB_USER}'
            DB_PASSWORD: '${DB_PASSWORD}'
        ports:
            - 9000:80
        volumes:
            - mixpost-storage:/var/www/html/storage/app
            - mixpost-logs:/var/www/html/storage/logs
        depends_on:
            - mysql
            - redis 
        restart: unless-stopped
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: '${DB_NAME}'
            MYSQL_USER: '${DB_USER}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'mixpost-mysql:/var/lib/mysql'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p ${DB_PASSWORD}"]
            retries: 3
            timeout: 5s
        restart: unless-stopped
    redis:
        image: 'redis:latest'
        command: redis-server --appendonly yes --replica-read-only no
        volumes:
            - 'mixpost-redis:/data'
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
        restart: unless-stopped  
volumes:
    mixpost-mysql:
        driver: local
    mixpost-redis:
        driver: local
    mixpost-storage:
        driver: local
    mixpost-logs:
        driver: local